### ISSUE TITLE
Unable to create injector, see the following errors:

### ISSUE THREAD

**Issue by ehosseinim** [aicenter/agentpolis-demo#7]
System specs:
$ mvn --version
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T21:00:29+02:00)
Maven home: /usr/local/Cellar/maven/3.6.1/libexec
Java version: 10, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-10.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.6", arch: "x86_64", family: "mac"

And I faced the problem while trying to run the demo. 
`mvn exec:java -Dexec.mainClass="cz.cvut.fel.aic.apdemo.DemoSimulation"`
Could you please help me with solving this issue?

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.101 s
[INFO] Finished at: 2019-06-05T00:31:32+02:00
[INFO] ------------------------------------------------------------------------
**[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project apdemo: An exception occured while executing the Java class. Unable to create injector, see the following errors:
[ERROR] 
[ERROR] 1) An exception was caught and reported. Message: org.opengis.referencing.datum.DatumFactory is not an ImageIO SPI class
[ERROR]   at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)
[ERROR] 
[ERROR] 2) Could not find a suitable constructor in cz.cvut.fel.aic.geographtools.util.Transformer. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
[ERROR]   at cz.cvut.fel.aic.geographtools.util.Transformer.class(Transformer.java:28)
[ERROR]   at cz.cvut.fel.aic.agentpolis.system.StandardAgentPolisModule.configure(StandardAgentPolisModule.java:82)
[ERROR] 
[ERROR] 2 errors**
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

<img width="1041" alt="Screen Shot 2019-06-05 at 12 37 17 AM" src="https://user-images.githubusercontent.com/16586218/58918314-1d368800-872a-11e9-876e-e1558097c6c4.png">

**Comment by F-I-D-O** [comment]
Hi, what version of Java are you using? It appears that the version of package org.geotools we depend on does not work with Java 9...

**Comment by ehosseinim** [comment]
Thank you for your response. As I mentioned above my java version is 10. 
Which java version org.geotools is compatible with?

**Comment by F-I-D-O** [comment]
We use it with Java 8, so it should be compatible with at least that version.

**Comment by ehosseinim** [comment]
How much workload it has for me to make it compatible with java 10?
Any suggestions from where should I start if I want to fix this issue with java version 10.

**Comment by F-I-D-O** [comment]
The real issue is: https://github.com/aicenter/geographtools/issues/2

There shouldn't be any workload, we just need to upgrade the Geotools version in pom and test if it works. But I don't know how long it takes before someone will be assigned to this task.

**Comment by F-I-D-O** [comment]
We updated the geotools dependency and now the demo can be compiled and run using JDK 11.
